### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/apache/solr/response/QueryResponseWriter on Solr 6.3

### ISSUE THREAD

**Issue by travisLilleberg** [IISH/oai4solr#14]
Hello, I'm trying to get this running on a core on my Solr 6.3 installation. The core is going to be used with a few [Hyrax](https://github.com/samvera/hydra-head) instances, so it uses the Hyrax conf files.

I've downloaded oai2-plugin-6.1.jar and put it in my ...../server/lib directory. I've pasted the requestHandler and queryResponseWriter from the documentation. I have an oai directory with an Identify.xml, and I'm just trying to get an Identify request working for now.

The core is called blacklight-core. The full files are below, thanks for any help.

**Longer Error:**
`org.apache.solr.common.SolrException: org/apache/solr/response/QueryResponseWriter
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:903)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:776)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:842)
	at org.apache.solr.core.CoreContainer.lambda$load$0(CoreContainer.java:498)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/apache/solr/response/QueryResponseWriter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:540)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:487)
	at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:699)
	at org.apache.solr.core.PluginBag.createPlugin(PluginBag.java:126)
	at org.apache.solr.core.PluginBag.init(PluginBag.java:226)
	at org.apache.solr.core.PluginBag.init(PluginBag.java:215)
	at org.apache.solr.core.SolrCore.initWriters(SolrCore.java:2358)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:852)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.apache.solr.response.QueryResponseWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more`

**solrconfig.xml:**
```xml
<config>
  <!-- NOTE: various comments and unused configuration possibilities have been purged
     from this file.  Please refer to http://wiki.apache.org/solr/SolrConfigXml,
     as well as the default solrconfig file included with Solr -->

  <abortOnConfigurationError>${solr.abortOnConfigurationError:true}</abortOnConfigurationError>

  <luceneMatchVersion>6.1.0</luceneMatchVersion>

  <directoryFactory name="DirectoryFactory" class="${solr.directoryFactory:solr.StandardDirectoryFactory}"/>

  <updateHandler class="solr.DirectUpdateHandler2">
    <updateLog>
      <str name="dir">${solr.core0.data.dir:}</str>
    </updateLog>
  </updateHandler>

  <!-- solr lib dirs -->
  <lib dir="${solr.install.dir:../../../..}/contrib/analysis-extras/lib" />
  <lib dir="${solr.install.dir:../../../..}/contrib/analysis-extras/lucene-libs" />

  <dataDir>${solr.data.dir:}</dataDir>

  <requestHandler name="search" class="solr.SearchHandler" default="true">
    <!-- default values for query parameters can be specified, these
         will be overridden by parameters in the request
      -->
     <lst name="defaults">
       <str name="defType">edismax</str>
       <str name="echoParams">explicit</str>
       <str name="q.alt">*:*</str>
       <str name="mm">2&lt;-1 5&lt;-2 6&lt;90%</str>
       <int name="qs">1</int>
       <int name="ps">2</int>
       <float name="tie">0.01</float>
       <!-- this qf and pf are used by default, if not otherwise specified by
            client. The default blacklight_config will use these for the
            "keywords" search. See the author_qf/author_pf, title_qf, etc 
            below, which the default blacklight_config will specify for
            those searches. You may also be interested in:
            http://wiki.apache.org/solr/LocalParams
       -->
        <str name="qf">
          id
          full_title_tesim
          short_title_tesim
          alternative_title_tesim
          active_fedora_model_ssi
          title_tesim
          author_tesim
          subject_tesim
          all_text_timv
        </str>
        <str name="pf">
          all_text_timv^10
        </str>

       <str name="author_qf">
          author_tesim
       </str>
       <str name="author_pf">
       </str>
       <str name="title_qf">
          title_tesim
          full_title_tesim
          short_title_tesim
          alternative_title_tesim
       </str>
       <str name="title_pf">
       </str>
       <str name="subject_qf">
          subject_tesim
       </str>
       <str name="subject_pf">
       </str>

       <str name="fl">
         *,
         score
       </str>

       <str name="facet">true</str>
       <str name="facet.mincount">1</str>
       <str name="facet.limit">10</str>
       <str name="facet.field">active_fedora_model_ssi</str>
       <str name="facet.field">subject_ssim</str>

       <str name="spellcheck">true</str>
       <str name="spellcheck.dictionary">default</str>
       <str name="spellcheck.onlyMorePopular">true</str>
       <str name="spellcheck.extendedResults">true</str>
       <str name="spellcheck.collate">false</str>
       <str name="spellcheck.count">5</str>

     </lst>
    <arr name="last-components">
      <str>spellcheck</str>
    </arr>
  </requestHandler>
  <requestHandler name="permissions" class="solr.SearchHandler" >
    <lst name="defaults">
      <str name="facet">off</str>
      <str name="echoParams">all</str>
      <str name="rows">1</str>
      <str name="q">{!raw f=id v=$id}</str> <!-- use id=666 instead of q=id:666 -->
      <str name="fl">
        id,
        access_ssim,
        discover_access_group_ssim,discover_access_person_ssim,
        read_access_group_ssim,read_access_person_ssim,
        edit_access_group_ssim,edit_access_person_ssim,
        depositor_ti,
        embargo_release_date_dtsi
        inheritable_access_ssim,
        inheritable_discover_access_group_ssim,inheritable_discover_access_person_ssim,
        inheritable_read_access_group_ssim,inheritable_read_access_person_ssim,
        inheritable_edit_access_group_ssim,inheritable_edit_access_person_ssim,
        inheritable_embargo_release_date_dtsi
      </str>
    </lst>
  </requestHandler>

  <requestHandler name="standard" class="solr.SearchHandler">
     <lst name="defaults">
       <str name="echoParams">explicit</str>
       <str name="defType">lucene</str>
     </lst>
  </requestHandler>

  <!-- for requests to get a single document; use id=666 instead of q=id:666 -->
  <requestHandler name="document" class="solr.SearchHandler" >
    <lst name="defaults">
      <str name="echoParams">all</str>
      <str name="fl">*</str>
      <str name="rows">1</str>
      <str name="q">{!raw f=id v=$id}</str> <!-- use id=666 instead of q=id:666 -->
    </lst>
  </requestHandler>
  <searchComponent name="spellcheck" class="solr.SpellCheckComponent">
    <str name="queryAnalyzerFieldType">textSpell</str>
    <!-- Multiple "Spell Checkers" can be declared and used by this component
      (e.g. for title_spell field)
      -->
    <lst name="spellchecker">
      <str name="name">default</str>
      <str name="field">spell</str>
      <str name="spellcheckIndexDir">./spell</str>
      <str name="buildOnOptimize">true</str>
    </lst>
  </searchComponent>

  <requestHandler name="/replication" class="solr.ReplicationHandler" startup="lazy" />

  <requestDispatcher handleSelect="true" >
    <requestParsers enableRemoteStreaming="true" multipartUploadLimitInKB="2048" />
  </requestDispatcher>

  <requestHandler name="/analysis/field" startup="lazy" class="solr.FieldAnalysisRequestHandler" />

  <requestHandler name="/oai" default="false" class="org.socialhistoryservices.api.oai.OAIRequestHandler">
    <!-- WT is the key for the queryResponseWriter (see below) -->
    <str name="wt">oai</str>
    <str name="oai_home">/oai</str>
    <!-- more configuration in this readme below -->
  </requestHandler>

  <queryResponseWriter name="oai" default="false" class="org.socialhistoryservices.api.oai.OAIQueryResponseWriter"/>
</config>
```

**managed-schema:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Solr managed schema - automatically generated - DO NOT EDIT -->
<schema name="Hydra" version="1.5">
  <uniqueKey>id</uniqueKey>
  <fieldType name="alphaSort" class="solr.TextField" omitNorms="true" sortMissingLast="true">
    <analyzer>
      <tokenizer class="solr.KeywordTokenizerFactory"/>
      <filter class="solr.ICUFoldingFilterFactory"/>
      <filter class="solr.TrimFilterFactory"/>
    </analyzer>
  </fieldType>
  <fieldType name="ancestor_path" class="solr.TextField">
    <analyzer type="index">
      <tokenizer class="solr.KeywordTokenizerFactory"/>
    </analyzer>
    <analyzer type="query">
      <tokenizer class="solr.PathHierarchyTokenizerFactory" delimiter="/"/>
    </analyzer>
  </fieldType>
  <fieldType name="boolean" class="solr.BoolField" sortMissingLast="true"/>
  <fieldType name="date" class="solr.TrieDateField" positionIncrementGap="0" precisionStep="0"/>
  <fieldType name="descendent_path" class="solr.TextField">
    <analyzer type="index">
      <tokenizer class="solr.PathHierarchyTokenizerFactory" delimiter="/"/>
    </analyzer>
    <analyzer type="query">
      <tokenizer class="solr.KeywordTokenizerFactory"/>
    </analyzer>
  </fieldType>
  <fieldType name="double" class="solr.TrieDoubleField" positionIncrementGap="0" precisionStep="0"/>
  <fieldType name="float" class="solr.TrieFloatField" positionIncrementGap="0" precisionStep="0"/>
  <fieldType name="int" class="solr.TrieIntField" positionIncrementGap="0" precisionStep="0"/>
  <fieldType name="location" class="solr.LatLonType" subFieldSuffix="_coordinate"/>
  <fieldType name="location_rpt" class="solr.SpatialRecursivePrefixTreeFieldType" geo="true" maxDistErr="0.000009" distErrPct="0.025" distanceUnits="degrees"/>
  <fieldType name="long" class="solr.TrieLongField" positionIncrementGap="0" precisionStep="0"/>
  <fieldType name="pid_text" class="solr.TextField" positionIncrementGap="100">
    <analyzer>
      <tokenizer class="solr.KeywordTokenizerFactory"/>
    </analyzer>
  </fieldType>
  <fieldType name="point" class="solr.PointType" subFieldSuffix="_d" dimension="2"/>
  <fieldType name="rand" class="solr.RandomSortField" omitNorms="true"/>
  <fieldType name="string" class="solr.StrField" sortMissingLast="true"/>
  <fieldType name="tdate" class="solr.TrieDateField" positionIncrementGap="0" precisionStep="6"/>
  <fieldType name="tdouble" class="solr.TrieDoubleField" positionIncrementGap="0" precisionStep="8"/>
  <fieldType name="text" class="solr.TextField" omitNorms="false">
    <analyzer>
      <tokenizer class="solr.ICUTokenizerFactory"/>
      <filter class="solr.ICUFoldingFilterFactory"/>
      <filter class="solr.TrimFilterFactory"/>
    </analyzer>
  </fieldType>
<fieldType name="text_en" class="solr.TextField" positionIncrementGap="100">
    <analyzer>
      <tokenizer class="solr.ICUTokenizerFactory"/>
      <filter class="solr.ICUFoldingFilterFactory"/>
      <filter class="solr.EnglishPossessiveFilterFactory"/>
      <filter class="solr.EnglishMinimalStemFilterFactory"/>
      <filter class="solr.TrimFilterFactory"/>
    </analyzer>
  </fieldType>
  <fieldType name="text_en_ng" class="solr.TextField" positionIncrementGap="100">
    <analyzer>
      <tokenizer class="solr.ICUTokenizerFactory"/>
      <filter class="solr.ICUFoldingFilterFactory"/>
      <filter class="solr.EnglishPossessiveFilterFactory"/>
      <filter class="solr.EnglishMinimalStemFilterFactory"/>
      <filter class="solr.TrimFilterFactory"/>
      <filter class="solr.EdgeNGramFilterFactory" maxGramSize="15" minGramSize="3"/>
    </analyzer>
  </fieldType>
  <fieldType name="text_ws" class="solr.TextField" positionIncrementGap="100">
    <analyzer>
      <tokenizer class="solr.WhitespaceTokenizerFactory"/>
      <filter class="solr.TrimFilterFactory"/>
    </analyzer>
  </fieldType>
  <fieldType name="tfloat" class="solr.TrieFloatField" positionIncrementGap="0" precisionStep="8"/>
  <fieldType name="tint" class="solr.TrieIntField" positionIncrementGap="0" precisionStep="8"/>
  <fieldType name="tlong" class="solr.TrieLongField" positionIncrementGap="0" precisionStep="8"/>
  <field name="_version_" type="long" indexed="true" stored="true"/>
  <field name="all_text_timv" type="text" indexed="true" termOffsets="true" stored="false" termPositions="true" termVectors="true" multiValued="true"/>
  <field name="full_title_ng" type="text_en_ng" multiValued="true" indexed="true" stored="false"/>
  <field name="id" type="string" multiValued="false" indexed="true" required="true" stored="true"/>
  <field name="id_ng" type="text_en_ng" multiValued="false" indexed="true" stored="false"/>
  <field name="lat" type="tdouble" multiValued="false" indexed="true" stored="true"/>
  <field name="lng" type="tdouble" multiValued="false" indexed="true" stored="true"/>
  <field name="original_pid_tesim" type="pid_text" multiValued="true" indexed="true" stored="true"/>
  <field name="timestamp" type="date" default="NOW" multiValued="false" indexed="true" stored="true"/>
 <dynamicField name="*_tesimv" type="text_en" indexed="true" termOffsets="true" stored="true" termPositions="true" termVectors="true" multiValued="true"/>
  <dynamicField name="*_dttsim" type="tdate" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_dbtsim" type="tdouble" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_tsimv" type="text" indexed="true" termOffsets="true" stored="true" termPositions="true" termVectors="true" multiValued="true"/>
  <dynamicField name="*_tesim" type="text_en" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_tesiv" type="text_en" indexed="true" termOffsets="true" stored="true" termPositions="true" termVectors="true" multiValued="false"/>
  <dynamicField name="*_itsim" type="tint" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_dtsim" type="date" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_dttsm" type="tdate" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_dttsi" type="tdate" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_ltsim" type="tlong" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_dbsim" type="double" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_dbtsm" type="tdouble" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_dbtsi" type="tdouble" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_ftsim" type="tfloat" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_llsim" type="location" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_bbox" type="location_rpt" indexed="true" stored="true"/>
  <dynamicField name="*_tsim" type="text" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_tsiv" type="text" indexed="true" termOffsets="true" stored="true" termPositions="true" termVectors="true" multiValued="false"/>
  <dynamicField name="*_tesm" type="text_en" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_tesi" type="text_en" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_ssim" type="string" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_isim" type="int" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_itsm" type="tint" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_itsi" type="tint" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_dtsm" type="date" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_dtsi" type="date" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_dtts" type="tdate" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_lsim" type="long" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_ltsm" type="tlong" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_ltsi" type="tlong" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_dbsm" type="double" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_dbsi" type="double" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_dbts" type="tdouble" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_fsim" type="float" multiValued="true" indexed="true" stored="true"/>
  <dynamicField name="*_ftsm" type="tfloat" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_ftsi" type="tfloat" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_llsm" type="location" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_llsi" type="location" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_tsm" type="text" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_tsi" type="text" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_tes" type="text_en" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_ssm" type="string" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_ssi" type="string" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_ism" type="int" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_isi" type="int" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_its" type="tint" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_dts" type="date" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_lsm" type="long" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_lsi" type="long" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_lts" type="tlong" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_dbs" type="double" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_fsm" type="float" multiValued="true" indexed="false" stored="true"/>
  <dynamicField name="*_fsi" type="float" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_fts" type="tfloat" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_bsi" type="boolean" multiValued="false" indexed="true" stored="true"/>
  <dynamicField name="*_lls" type="location" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_ts" type="text" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_ss" type="string" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_is" type="int" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_ls" type="long" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_fs" type="float" multiValued="false" indexed="false" stored="true"/>
  <dynamicField name="*_bs" type="boolean" multiValued="false" indexed="false" stored="true"/>
  <copyField source="full_title_tesim" dest="full_title_ng" maxChars="3000"/>
  <copyField source="id" dest="id_ng" maxChars="3000"/>
  <copyField source="*_tesim" dest="all_text_timv" maxChars="3000"/>
</schema>```

**Comment by lwo** [comment]
I cannot explain yet why the QueryResponseWriter interface is not found as it is part of the solr-core artifact.

What would happen if you remove the OAI2 declarations and in stead use a buildin plugin like the  JSONResponseWriter which  extends QueryResponseWriter like so:

`<queryResponseWriter name="json" class="org.apache.solr.request.JSONResponseWriter" />`

?

**Comment by travisLilleberg** [comment]
I get an error saying:

`rg.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Error loading class 'org.apache.solr.request.JSONResponseWriter'`

but, when I do the following . . .
```xml
<queryResponseWriter name="json" default="false" class="solr.JSONResponseWriter"/>
<requestHandler name="/test" default="false" class="solr.SearchHandler">
  <str name="wt">oai</str>
  <str name="oai_home">/oai</str>
</requestHandler> 
```
 . . . the core stops throwing errors.

**Comment by lwo** [comment]
That looks ok. So at this stage I really like to get my hands on your Solr installation (distribution and configuration) and run it locally. Could you place it somewhere where I can download it and give it a spin?

**Comment by travisLilleberg** [comment]
I'll send a dropbox link to the email on your profile here, is that ok?

**Comment by lwo** [comment]
ok

**Comment by lwo** [comment]
There are two issues.

1. A bug, see #15

2.  Then a configuration.... This will ensure the plugin is loaded after the base core solr libraries and prevent the NoClassDefFound error:
a. delete your plugin 
b. make a directory contrib/oai and download the new plugin with the patch for #15 in there
c. declare the library directory in your solrconfig:
`<lib dir="${solr.install.dir:../../../..}/contrib/oai" />`

Then try it out, run your solr instance:
$ bin/solr start

and in your browser:
http://localhost:8983/solr/blacklight-core/oai?verb=Identify

This shows me this response:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><OAI-PMH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd" xmlns="http://www.openarchives.org/OAI/2.0/"><responseDate>2017-10-19T15:46:08Z</responseDate><request verb="Identify"></request><Identify><repositoryName>Tufts Digital Repository</repositoryName><baseURL>http://dl.tufts.edu:8983/solr/oai</baseURL><protocolVersion>2.0</protocolVersion><adminEmail>travis.lilleberg@tufts.edu</adminEmail><earliestDatestamp>1970-01-01T00:00:00Z</earliestDatestamp><deletedRecord>transient</deletedRecord><granularity>YYYY-MM-DDThh:mm:ssZ</granularity><compression>none</compression><description><oai-identifier xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai-identifier http://www.openarchives.org/OAI/2.0/oai-identifier.xsd" xmlns="http://www.openarchives.org/OAI/2.0/oai-identifier" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><scheme>oai</scheme><repositoryIdentifier>http://dl.tufts.edu:8983</repositoryIdentifier><delimiter>:</delimiter><sampleIdentifier>oai:http://dl.tufts.edu:UP029.009.012.00039</sampleIdentifier></oai-identifier></description></Identify></OAI-PMH>`

Does this work out for you?

**Comment by travisLilleberg** [comment]
Works perfectly! Thanks for all the help.

**Comment by lwo** [comment]
You too, thanks for the report.
