### ISSUE TITLE
ListSets throws NoSuchMethodError

### ISSUE THREAD

**Issue by inghamn** [IISH/oai4solr#5]
When trying to hit:
http://localhost:8080/solr/dcs/oai/?verb=ListRecords&metadataPrefix=solr

The response is only a 

``` xml
<OAI-PMH xsi:nil="true"/>
```

In the Tomcat log is the error:

```
ERROR org.apache.solr.servlet.SolrDispatchFilter  – null:java.lang.RuntimeException: java.lang.NoSuchMethodError: org.apache.lucene.search.SortField.<init>(Ljava/lang/String;IZ)V
        at org.apache.solr.servlet.SolrDispatchFilter.sendError(SolrDispatchFilter.java:796)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:448)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:217)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NoSuchMethodError: org.apache.lucene.search.SortField.<init>(Ljava/lang/String;IZ)V
        at org.socialhistoryservices.api.oai.OAIRequestHandler.runQuery(OAIRequestHandler.java:258)
        at org.socialhistoryservices.api.oai.OAIRequestHandler.runQuery(OAIRequestHandler.java:246)
        at org.socialhistoryservices.api.oai.OAIRequestHandler.buildQuery(OAIRequestHandler.java:164)
        at org.socialhistoryservices.api.oai.OAIRequestHandler.handleRequestBody(OAIRequestHandler.java:95)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1916)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:780)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:427)
        ... 16 more
```

**Comment by lwo** [comment]
Thanks for the report. Which Solr version are you using ?

**Comment by inghamn** [comment]
This is with Solr 4.7.0

**Comment by lwo** [comment]
Yes, this plugin is using Solr 3.x class dependencies.

To make it work for Solr 4.x the code needs to be re factored and released in a separate branch. If you need a Solr 4 plugin, then please add a new issue.
